# Project
kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G -XX:ThreadStackSize=4096 -XX:CompilerThreadStackSize=4096
org.gradle.daemon=false
org.gradle.parallel = true

#Plugins
javaVersion = 21
kotlinVersion = 2.0.21
moddevVersion = 1.0.21

#Minecraft
minecraftVersion=1.21.1
minecraftVersionRange = [1.21.1, 1.21.2)
parchmentMCVersion = 1.21
parchmentVersion = 2024.11.10

# Mod
version=0.0.1
mavenGroup=git.redspyboy.redstms
modId=redstms
modName=Red's TMs
archiveBaseName=redstms
modAuthor=Redspyboy
description=Cobblemon addon implementing TMs in the Cobblemon Style
license=CC0-1.0
credits=Redspyboy
enabledPlatforms=fabric,neoforge

#mixin
mixinVersion = 0.8.5
mixinExtrasVersion = 0.3.5

#Neoforge
neoforgeVersion = 21.1.80
neoforgeVersionRange=[21.0,21.1)
neoformVersion = 1.21.1-20240808.144430
forgeConfigApiVersion=21.1.0


#Fabric
fabricLoaderVersion = 0.16.9
fabricApiVersion = 0.109.0+1.21.1

#Architectury
architecturyVersion = 13.0.8
architecturyLoomVersion = 1.11-SNAPSHOT
architecturyPluginVersion = 3.4-SNAPSHOT

#Kotlin APIs
kotlinForForgeVersion = 5.10.0
kotlinForForgeRange = [5.10, )
fabricKotlinVersion = 1.12.3+kotlin.2.0.21


